### ISSUE TITLE
mac上不行啊

### ISSUE THREAD

**Issue by badboy-tian** [wingcd/wechat_taptap#1]
```
➜  Desktop sudo python ./taptap.py
/sdcard/screenshot.jpg: 1 file pulled. 10.5 MB/s (60494 bytes in 0.005s)
/sdcard/screenshot.jpg: 1 file pulled. 9.3 MB/s (60494 bytes in 0.006s)
Traceback (most recent call last):
  File "./taptap.py", line 196, in <module>
    threading.Thread(target = run).run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./taptap.py", line 178, in run
    x0,y0 = findRole()
  File "./taptap.py", line 86, in findRole
    w,h = template.shape[::-1]
AttributeError: 'NoneType' object has no attribute 'shape'
➜  Desktop 

```

**Comment by wingcd** [comment]
现在只在windows上测试过哈。没mac环境的，不过看样子，好像没找到temp.png这张图片，可能要设置下运行环境
