### ISSUE TITLE
运行报错啊。。python3.5.2

### ISSUE THREAD

**Issue by wysainty** [wingcd/wechat_taptap#2]
Traceback (most recent call last):
  File "E:\for github\wechat_taptap\taptap.py", line 195, in <module>
    threading.Thread(target = run).run()
  File "D:\python\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "E:\for github\wechat_taptap\taptap.py", line 176, in run
    ready()
  File "E:\for github\wechat_taptap\taptap.py", line 76, in ready
    image=cv2.resize(image,(h,w),interpolation=cv2.INTER_CUBIC)
TypeError: integer argument expected, got float

**Comment by wingcd** [comment]
python2.7写的
